"""empty message

Revision ID: 800ed065597b
Revises: 
Create Date: 2022-02-24 12:55:55.102269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800ed065597b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inv',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=50), nullable=True),
    sa.Column('item_desc', sa.String(length=250), nullable=True),
    sa.Column('item_price', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name_first', sa.String(length=150), nullable=True),
    sa.Column('name_last', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inv.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cart')
    op.drop_table('user')
    op.drop_table('inv')
    # ### end Alembic commands ###
